name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print multi-line
        run: |
          echo "First output"
          echo "Second output"
      - name: Print goodbye
        run: echo "Done - bye!"
    
